name = "mint-agi-inline-editor"
main = "src/index.js"
compatibility_date = "2024-09-25"

routes = [
  { pattern = "agi-editor.mintresearch.org", custom_domain = true }
]

[vars]
ALLOWED_ORIGINS = "https://mintresearch.org,https://www.mintresearch.org"

[[kv_namespaces]]
binding = "CONTENT_OVERRIDES"
id = "0db5c6f599784d08990cab6a912e83b8"
