name = "mint-agif-router"
main = "src/index.js"
compatibility_date = "2024-09-25"
workers_dev = true
preview_urls = false

routes = [
  { pattern = "fellowship.mintresearch.org", zone_name = "mintresearch.org", custom_domain = true },
  { pattern = "agif1.mintresearch.org", zone_name = "mintresearch.org", custom_domain = true },
  { pattern = "agif2.mintresearch.org", zone_name = "mintresearch.org", custom_domain = true },
  { pattern = "agif3.mintresearch.org", zone_name = "mintresearch.org", custom_domain = true },
  { pattern = "mintresearch.org/agif*", zone_name = "mintresearch.org" },
  { pattern = "mintresearch.org/should-we-build-agi*", zone_name = "mintresearch.org" },
  { pattern = "mintresearch.org/agi-institutions*", zone_name = "mintresearch.org" },
  { pattern = "mintresearch.org/societal-adaptation*", zone_name = "mintresearch.org" }
]

[assets]
directory = "../public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"
not_found_handling = "none"
