name = "mint-agif-router"
main = "src/index.js"
compatibility_date = "2024-09-25"
workers_dev = true
preview_urls = false

routes = [
  { pattern = "agif1.mintresearch.org", custom_domain = true },
  { pattern = "agif2.mintresearch.org", custom_domain = true },
  { pattern = "agif3.mintresearch.org", custom_domain = true }
]
