import assert from 'node:assert/strict';
import fs from 'node:fs';

const deck = fs.readFileSync('public/FDC-deck.html', 'utf8');
const wrapper = fs.readFileSync('public/FDC.html', 'utf8');
const shellScript = fs.readFileSync('public/assets/presentation-shell.js', 'utf8');
const shellCss = fs.readFileSync('public/assets/presentation-shell.css', 'utf8');

assert.ok(!deck.includes('@chenglou/pretext'), 'runtime fitting must not load the Safari-blocking Pretext layout path');
assert.ok(deck.includes('return slide.clientWidth && slide.clientHeight ? 1 : MIN_FIT_SCALE;'), 'each visible slide must start at authored type size and shrink only for measured containment');
assert.ok(deck.includes('function fitSlideWithinFrame'), 'every slide must use bounded frame fitting');
assert.ok(deck.includes('FIT_SEARCH_ITERATIONS = 10'), 'frame fitting must use a bounded search');
assert.ok(deck.includes('const index = cur;\n  const slide = slides[index];'), 'each pass must retain the identity of its visible slide');
assert.ok(deck.includes('.slide.fit-measuring { transform: none; transition: none; overflow: hidden; }'), 'candidate geometry must not create scrollbars that retrigger iframe resize');
assert.ok(deck.includes("secName.textContent=slides[n].dataset.name||'';fitSlides();"), 'navigation must fit the newly visible slide before paint');
assert.ok(deck.includes('.fi { opacity: 1; transform: none; transition: none; }'), 'Safari slide navigation must not leave text transparent');
assert.ok(deck.includes('.slide.active { opacity: 1; visibility: visible;'), 'Safari must not composite transformed inactive slides over the current slide');
assert.ok(deck.includes("content.style.transform = `scale(${scale})`;"), 'Safari fitting must use rendered transform geometry');
assert.ok(!deck.includes('content.style.zoom'), 'Safari fitting must not depend on inconsistent CSS zoom geometry');
assert.ok(deck.includes("content.style.transform = 'none';"), 'candidate measurement must use untransformed text geometry');
assert.ok(deck.includes("content.style.flex = '0 0 auto';"), 'inverse-size compensation must not be collapsed by flex shrink');
assert.ok(deck.includes('origin.top + (content.bottom - origin.top) * scale'), 'candidate bounds must be projected into the visible frame');
assert.ok(deck.includes('fitFrame = requestAnimationFrame(() => {'), 'resize fitting must be throttled to the next paint frame');
assert.ok(!deck.includes('requestAnimationFrame(resolve)'), 'candidate measurement must not wait on animation frames while oversized');
assert.ok(deck.includes("content.style.height = `${100 / scale}%`;"), 'scaled slide backgrounds must continue filling the visible stage');
assert.ok(deck.includes("window.addEventListener('resize', scheduleFit)"), 'fitter must react to actual iframe viewport changes');
assert.ok(!deck.includes('new ResizeObserver(scheduleFit)'), 'fitter must not observe layout writes that cancel its own search');
assert.ok(!deck.includes("if (!matchMedia('(min-width: 901px)').matches)"), 'narrow framed decks must not bypass fitting');
assert.ok(deck.includes('document.createTreeWalker(slide, NodeFilter.SHOW_TEXT)'), 'containment must measure rendered text nodes');
assert.ok(deck.includes('projected.top >= frame.top'), 'containment must keep edge-aligned structural labels inside the top edge');
assert.ok(deck.includes('projected.right <= frame.right - FRAME_INSET'), 'containment must include a safe right inset');
assert.ok(deck.includes('projected.bottom <= frame.bottom - FRAME_INSET'), 'containment must include a safe bottom inset');
assert.ok(deck.includes('projected.left >= frame.left'), 'containment must keep edge-aligned structural labels inside the left edge');
assert.ok(deck.includes('belowPreferredFloor: scale < preferredFloor'), 'readability must be diagnostic rather than a hard overflow floor');
assert.ok(deck.includes("slide.classList.add('fit-scroll-fallback');"), 'failed containment must restore readable scrolling');
assert.ok(deck.includes("window.__fdcFit.status = 'fit-error';"), 'fitting exceptions must be recorded');
assert.ok(deck.includes("finally {\n    slide.classList.remove('fit-measuring');"), 'measurement state must always be cleaned up');
assert.ok(deck.indexOf('fitSlides();\n  if (!document.fonts) return;') < deck.indexOf('document.fonts.ready.then(fitSlides)'), 'initial fitting must run before waiting for web fonts');
assert.ok(deck.includes('document.fonts.ready.then(fitSlides)'), 'late font readiness must trigger a refit');
assert.ok(deck.includes("document.fonts.addEventListener?.('loadingdone', fitSlides)"), 'subsequent web-font loads must trigger a refit');
assert.ok(deck.includes("event.data === 'mint-presentation-resize'"), 'the deck must accept same-origin shell resize notifications');
assert.ok(deck.includes('window.refitFdcSlides = fitSlides'), 'the deck must expose a same-origin refit hook to its shell');
assert.ok(wrapper.includes('src="/FDC-deck.html?v=20260715.26"'), 'wrapper must bypass stale iframe caches');
assert.ok(wrapper.includes('src="/assets/presentation-shell.js?v=20260715.26"'), 'wrapper must bypass stale shell-script caches');
assert.ok(shellScript.includes("frame.contentWindow.postMessage('mint-presentation-resize', window.location.origin)"), 'the shell must notify the deck of observed iframe size changes');
assert.ok(shellScript.includes('frameObserver.observe(frame)'), 'the shell must observe the actual iframe element size');
assert.ok(shellScript.includes("frame.contentWindow.dispatchEvent(new Event('resize'))"), 'same-origin decks must receive an explicit resize event');
assert.ok(shellScript.includes('frame.contentWindow.refitFdcSlides?.()'), 'same-origin decks must be refitted directly after shell changes');
assert.ok(shellScript.includes('setTimeout(notifyFrameResize, 350)'), 'the shell must refit after its inset transition completes');
assert.ok(shellScript.includes("event.propertyName === 'inset' || event.propertyName === 'padding'"), 'the shell must refit when its actual transition finishes');
assert.ok(shellScript.includes("style.setProperty('--presentation-status-h', statusline.getBoundingClientRect().height + 'px')"), 'shell must reserve the measured status-bar height');
assert.ok(shellScript.includes('chromeObserver.observe(statusline)'), 'shell must observe status-bar size changes');
assert.ok(shellCss.includes('--presentation-status-h: 49px'), 'mobile fallback must match the two-row status bar');

console.log('FDC frame-fit source contract passed: synchronous navigation, resize/font refits, containment fallback, and shell chrome reservation.');
